### ISSUE TITLE
Support for Portable mode(Using SendTo Menu)

### ISSUE THREAD

**Issue by MacgyverJohnson** [apsun/GoogleImageShell#5]
Hello there @apsun 
This is a really cool app. Could support for SendTo menu me added? 
Thanks

**Comment by apsun** [comment]
This wouldn't really help portability, since you will still have to "install" the app to the SendTo menu. What are you trying to accomplish?

**Comment by MacgyverJohnson** [comment]
No I have to just create a shortcut on Sendto Menu folder...Many portable apps that natively support drag n drop have SendTo menu support.....Its like this...You are on a guest/Public PC and dont want to clutter the explorer shell context menu with lots of new entries( in case u have lot of sendto menu shortcuts)....
Also u know that there's extended Sento menu which is only visible if SHIFT key is pressed(one way to add to this extended sendto menu is create shortcut in "C:\Users\<Username>\" folder .... 
About having to install...not necissarily. portableapps.com (.paf) format launcher created using NSIS can automatically add SendTO menu entries on executable launch and Removes entries on execuable exit...therefore leaving no trace(stealth) and best thing is no need for Admin rights
Thanks

**Comment by apsun** [comment]
You can already make a SendTo shortcut yourself. Just put " search" after the executable path. Like this:

```
path\to\GoogleImageShell.exe search
```

I don't see how adding this functionality within the app would make a difference. This app does not run persistently in the background. It starts when you click the menu, and exits after it opens your browser. "Installing" it just creates a few items in the registry, and "uninstalling" it removes those items.

**Comment by MacgyverJohnson** [comment]
Thanks senpai!!!
