### ISSUE TITLE
can i know program location in registry windows 10 !

### ISSUE THREAD

**Issue by mustafaabobakr** [apsun/GoogleImageShell#9]
want to add Icon string

**Comment by apsun** [comment]
[`Software\Classes\SystemFileAssociations\<filetype>\shell`](https://github.com/apsun/GoogleImageShell/blob/master/GoogleImageShell/ShortcutMenu.cs)

**Comment by mustafaabobakr** [comment]
there is no **Key** for _GoogleImageShell_

![image](https://user-images.githubusercontent.com/27288406/33804408-c6f9bcaa-ddac-11e7-98ec-70c4e4ec1de4.png)
to add an icon :-
-i search for key ex googleSearchImage 
-add a string "Icon" with value of any icon or exe using (copy as a path)
like this 
![image](https://user-images.githubusercontent.com/27288406/33804687-cc842290-ddb2-11e7-9a82-a3b9597fa46c.png)

**Comment by apsun** [comment]
If you didn't install the program for all users, you should look in the CURRENT_USER hive instead of the LOCAL_MACHINE hive.

**Comment by mustafaabobakr** [comment]
Thank you 
![image](https://user-images.githubusercontent.com/27288406/33806496-bd7851a8-ddd1-11e7-987e-fb1bfcae1574.png)

**Comment by apsun** [comment]
You're welcome :-)
